### ISSUE TITLE
Errors counter not updating

### ISSUE THREAD

**Issue by cleptric** [getsentry/spotlight#117]
![image](https://github.com/getsentry/spotlight/assets/6617432/ffc5dd35-ec0f-4217-bcf5-30d26284ee79)

**Comment by HazAT** [comment]
Generally, counters are a bit wacky - in Spotlight you see 4 transactions but the small counter shows way more - that's because we count incoming envelopes but in Spotlight we group them.

**Comment by Shubhdeep12** [comment]
Hi @HazAT it seems like in the Errors tab -  we list all events which are not transaction. 
But when it comes to showing the counter - we are checking the events without any type which is causing the difference in the list and the counter.
