### ISSUE TITLE
Toolbar: Fix missing paddings and span tree view

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/spotlight#126]
Evaluate if necessary padding has been applied to all visual elements (including states like hover etc., see screenshot)

<img width="1094" alt="Screenshot 2023-11-23 at 18 09 26" src="https://github.com/getsentry/spotlight/assets/7096858/720a59a7-4b21-4b86-b5db-a3858afaff95">

- the contents in the overlay have no padding left (9ms)
- the hover state of the HTTP span shows that the background is not reaching into the left enough
- the tree rendering of spans seem off, this is not so obvious if you have additional information present like "db", but becomes clear once this is missing. Maybe we can hide the additional dash in case there is no such value like "db"

<img width="67" alt="Screenshot 2023-11-23 at 19 13 57" src="https://github.com/getsentry/spotlight/assets/7096858/42dcbba8-9200-47d3-bc29-3dea50a30611">

**Comment by Lms24** [comment]
@dcramer I think you fixed this yesterday, right?

**Comment by HazAT** [comment]
I did also a few - not sure if I caught everything but we can close it I think
