### ISSUE TITLE
Feature: Spotlight just for Frontend

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#133]
Make Spotlight a mode that, if it fails to connect to the sidecar from the frontend and can try to directly send stuff from the Sentry Browser SDK to the Overlay.
For pure frontends, this would make it possible to run it without the sidecar.

**Comment by lforst** [comment]
A really cool architecture here would be to have a webworker that intercepts all the requests from the browser and acts as a sidecar, until it detects an actual sidecar and then forwards/proxies everything.

**Comment by Lms24** [comment]
Spotlight overlay already has an event target we can use to communicate. Maybe we send events via the target to the sentry datacache.

**Comment by BYK** [comment]
Closing this out as this is now a reality. The [drop-in IIFE CDN bundle](https://spotlightjs.com/setup/html/) works especially well in this scenario.
