### ISSUE TITLE
Docs: Typos in docs and a extension for recommendation

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/spotlight#135]
- I was going through the docs, and while reading I found some typos so I fixed them.

- Also, how about adding this https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker extension to the recommendations?

Can I create a PR for both points?

**Comment by Lms24** [comment]
Hi, thanks for writing in! Sure, feel free to open a PR. Happy to review :)
