### ISSUE TITLE
Multiple projects with same sidecar but different overlays 

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/spotlight#139]
I added the overlay in my personal app to test.
Also, I ran the spotlight/website locally which is also using Sidecar.

Both are using sidecar at port 8969

I just want to raise this concern that I am getting the same errors and traces on both apps. 
Is this correct behaviour?

I think the spotlight should be specific to a project at a time. 
If the user wants to test different apps - we should host the sidecar at a different port or something else. 

Responses would be appreciated.

Thanks

**Comment by HazAT** [comment]
Valid question - right now we really want to optimize to have one Spotlight running.
Also, the sidecar only needs to run once, since it's completely project/language agnostic.

So I will put this on `2.0` milestones for things to consider.

**Comment by dcramer** [comment]
We'll want to put more thought into this general problem. I think for now its ok, but there is obvious a world where we'd prefer to somehow set a marker for processes and traces to know which ones we care about.

Right now it basically operates like Chrome devtools and the Preserve option, which is fine but also confusing at times.
