### ISSUE TITLE
Spotlight Overlay needs `process` to be set, doesn't work with Rails + importmaps out of the box

### ISSUE THREAD

**Issue by natikgadzhi** [getsentry/spotlight#141]
### Environment

- Rails 7.0 with importmaps (yeah yeah, I know, I just needed a quick example though).
- `@spotlightjs/overlay@0.0.16`

### Steps to Reproduce

1. So, take a clean empty new Rails app
2. Add `@spotlightjs/overlay` via importmap, so it looks like this:
  ```ruby
   # Pin npm packages by running ./bin/importmap

  pin "application", preload: true
  pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
  pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
  pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
  pin_all_from "app/javascript/controllers", under: "controllers"
  pin "@spotlightjs/overlay", to: "https://ga.jspm.io/npm:@spotlightjs/overlay@0.0.16/dist/sentry-spotlight.js"
  ```
3. Add the init code to `application.js`:
  ```ruby
  // Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
  import "@hotwired/turbo-rails"
  import "controllers"
  
  import * as Spotlight from '@spotlightjs/overlay';
  Spotlight.init();
  ```
4. Load the page

### Expected Result

I want the Spotlight overlay! 

### Actual Result

```
Uncaught ReferenceError: process is not defined
    <anonymous> sentry-spotlight.js:2150
```

Specific check that fails: `process.env.NODE_ENV`. I don't see that particular check in `packages/overlay`, diggin in to see what / how it's imported. 

I was just testing sentry-ruby's Spotlight PR. I'll make that one work first, then see if I can fix this in a cheap way, too.

**Comment by dcramer** [comment]
Gonna dig real quick maybe easy fix

**Comment by natikgadzhi** [comment]
I'm looking too — should be straightforward, just trying to figure out what checks for `process.env.NODE_ENV` or `process.*` really, and making it more defensive.

**Comment by dcramer** [comment]
Looks like this might be in React/Vite :(

process.env.NODE_ENV === "production"

Might be related to https://github.com/vitejs/vite/issues/1973

**Comment by natikgadzhi** [comment]
Related: https://github.com/rails/importmap-rails/issues/162

**Comment by dcramer** [comment]
I believe the issue is the prod bundler has react.development in it

**Comment by natikgadzhi** [comment]
> I believe the issue is the prod bundler has react.development in it

https://vitejs.dev/guide/build.html#library-mode 👀

**Comment by natikgadzhi** [comment]
Oh gawd https://github.com/rails/importmap-rails/issues/65#issuecomment-1000389955

**Comment by natikgadzhi** [comment]
<img width="1383" alt="Screenshot 2023-11-27 at 3 34 09 PM" src="https://github.com/getsentry/spotlight/assets/43633/65807c7e-0398-4517-a2a6-5f92a271c972">

It's alive, sort of.

**Comment by dcramer** [comment]
> <img alt="Screenshot 2023-11-27 at 3 34 09 PM" width="1383" src="https://private-user-images.githubusercontent.com/43633/286053528-65807c7e-0398-4517-a2a6-5f92a271c972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzA2MzUsIm5iZiI6MTcwMTEzMDMzNSwicGF0aCI6Ii80MzYzMy8yODYwNTM1MjgtNjU4MDdjN2UtMDM5OC00NTE3LWEyYTYtNWY5MmEyNzFjOTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAwMTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMmNmYTBiNmE5ZjVjYzQ0ZjU1MGZkMzNkOTMxZjEzNzRlZmFmYzYyNmM0NjllZjhjODdlY2Y5MmVjMGIzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XD5URx1_k_BPip83kEv0wCMv0mgU0WOTSvHmlr-1OlE">
> It's alive, sort of.

Gross and awesome at the same time 😆

**Comment by Lms24** [comment]
Hi @natikgadzhi 

Is there something left to do on our end or is this indeed a Rails issue? (I know next to nothing about Rails, so probably missing something. Sorry!)

**Comment by natikgadzhi** [comment]
Nah, not worth it at this point. Let’s close this.
