### ISSUE TITLE
Should we show multi-line error messages, or trim the ^^^^ in the end of the error message?

### ISSUE THREAD

**Issue by natikgadzhi** [getsentry/spotlight#143]
## Environment

- Rails 7.0.3
- sentry-ruby from https://github.com/getsentry/sentry-ruby/pull/2175 here
- Spotlight 0.0.16
- Sidecar 0.0.11

## Problem

When Spotlight shows an error from Ruby (Any multiline error that tries to show you the cause of the error position in source code will do), it has a bunch of `^^^^^^^` highlighting where the error was. 

Sentry web UI shows the multi-line error highlighting the cause, but Spotlight doesn't yet do that. 

| <img width="2660" alt="Screenshot 2023-11-27 at 4 28 59 PM" src="https://github.com/getsentry/spotlight/assets/43633/ca7bf9c4-70bf-4ae8-b7db-5f6f06607002"> | <img width="2660" alt="Screenshot 2023-11-27 at 4 27 46 PM" src="https://github.com/getsentry/spotlight/assets/43633/ffc9811e-14d3-43d6-8488-a7991a7b5984">|
| --- | --- |

## Solutions

We should probably format the multiline error messages.

**Comment by dcramer** [comment]
We should probably render this with preformatted text. IMO important to represent what it looks like elsewhere.

Marking for fix before 1.0

**Comment by HazAT** [comment]
Fixed 
<img width="847" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/bf38e95c-bac9-4c82-a941-da0a8588189b">
