### ISSUE TITLE
Spotlight shows captured messages as `Unknown Event`

### ISSUE THREAD

**Issue by natikgadzhi** [getsentry/spotlight#145]
## Environment

- Rails 7.0.3
- sentry-ruby from https://github.com/getsentry/sentry-ruby/pull/2175 here
- Spotlight 0.0.16
- Sidecar 0.0.11

## Problem

`Sentry.capture_message("hello, world!")` shows up in Spotlight, BUT! 

- The "Errors" tab still shows zero instead of one, i.e. message is not counted. Maybe that's because it does not have a title, but likely because it's not an error event?
- The item's title in the list of Errors is blank.
- When you click into it, it renders as `Unknown Event`

| <img width="2660" alt="Screenshot 2023-11-27 at 4 41 40 PM" src="https://github.com/getsentry/spotlight/assets/43633/e1ce9d62-ac2c-4f62-90ac-921f1ebd892c"> | <img width="2660" alt="Screenshot 2023-11-27 at 4 41 44 PM" src="https://github.com/getsentry/spotlight/assets/43633/9bb528e5-c6bd-4dc5-b2ac-7ce115df919b"> |
| --- | --- |

**Comment by natikgadzhi** [comment]
https://github.com/getsentry/spotlight/blob/dc616e4f15d8fd4d99a1c00c0ddc5cde3e412e68/packages/overlay/src/integrations/sentry/components/EventList.tsx#L10 — seems relatively straightforward to add support for non-error events on the data lavel. 

Not sure if they should live in the Errors tab, though. We could rename Errors to Events and put them there.

**Comment by HazAT** [comment]
Same https://github.com/getsentry/spotlight/issues/142#issuecomment-1829796976
