### ISSUE TITLE
(low prio): Open with keypress

### ISSUE THREAD

**Issue by Lms24** [getsentry/spotlight#158]
Something like Cmd+F12 (similar to dev tools) could open/close spotlight.

With ESC now being primarily used to navigate back, a second key (combination) might be handy.

**Comment by Shubhdeep12** [comment]
How about Ctrl + Shift + S

S stands for Sentry and Spotlight 😅

**Comment by Lms24** [comment]
Sure that also works 😅

**Comment by Shubhdeep12** [comment]
So should we add this? Let me know, i'll push a commit for this.

**Comment by Lms24** [comment]
Yes, feel free to open a PR! If you do it, please verify that the integration with the Astro dev overlay still works. Testing with the Astro playground demo is probably helpful.

**Comment by Shubhdeep12** [comment]
Hi @Lms24 looks like we completed this one and we are using ctrl/cmd + F12 for this.

Should we close this issue now?

**Comment by Lms24** [comment]
Huh right, not sure why this is still open, closing!
