### ISSUE TITLE
Fix Vite/Astro (local) Stacktraces

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#16]
This is how the stacktrace looks like when throwing an error on a button click:
<img width="851" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/af76a5a9-cd68-419b-9992-ef9fedd99a76">
which ofc is correct because it's just a generated HTML page.

What we actually want is to see a stacktrace and reference a file like this:

<img width="804" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/6a1d5192-0377-44cb-b0a5-5753017b8511">

**Comment by Lms24** [comment]
Removing this from #17 for the moment. We'll come back and revisit this later but it requires more research to determine if using data attributes that were recently added to Astro is possible
