### ISSUE TITLE
Top Level counter counting the wrong thing

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#176]
<img width="75" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/0907e728-b9df-4676-bca0-ccf7ff9d7d68">
The counter on the trigger shows
<img width="575" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/c6431581-c4d3-4ee2-9e0c-83514dbcf070">

It actually counts all transactions and not the traces - feels non-intuitive - maybe we should only show top level counts on the trigger

**Comment by Lms24** [comment]
Ahh I see this is a limitation of how we currently count. We can probably adjust the `processEvent` API to return a custom count and in the sentry integration return the count of errors+traces. Just need to think a bit how to do this properly.

**Comment by Lms24** [comment]
@Shubhdeep12 This could also work and I think it's easier to understand than the thing we have right now. Good idea! We just need to figure out how we can pass the count back to the trigger button but I'm sure it's doable.
