### ISSUE TITLE
Run Sidecar on custom port

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/spotlight#184]
Hi, 

Feature Request - I believe it would be beneficial to provide users with the option to run the sidecar on different port(if needed).
Usecase - One potential use case for this feature is when a user wants to run Spotlight for multiple applications at the same time.
Solution - one possible solution is that `npx @spotlightjs/spotlight optionalCustomPORT`

If this is a valid request, please confirm, I'll push a commit and raise a PR for this.
Thanks

**Comment by HazAT** [comment]
Yes, we can just read `process.args` and add an optional argument to `setupSidecar`

**Comment by Shubhdeep12** [comment]
Yes, i was thinking about the same. I'll create a PR in sometime. 
Thanks for confirming.
