### ISSUE TITLE
Astro instructions unclear on Sentry

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#200]
Sentry is not required - as in the DSN/config is not required (and we should confirm it doesnt error out) - but the docs make it seem like it is.

https://spotlightjs.com/setup/astro/

**Comment by Lms24** [comment]
@dcramer Does the documentation still need improvement? I think you already did something in the last days, right?

**Comment by dcramer** [comment]
Yeah I cleaned this one up
