### ISSUE TITLE
Improve sidecar logging

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#201]
Right now it spits out quite a bit of debug information.

1. Consider making some of the log statements debug statements (e.g. received an event)
2. Consider DI to make it so e.g. the Astro logger could be used in Astro (I dont think this is feasible fwiw).

See also https://www.npmjs.com/package/debug

**Comment by dcramer** [comment]
Not yet though we’re on the home stretch for 1.0 so probably will pick this up in a few hours

**Comment by Lms24** [comment]
I think we can relatively easily DI the logger. Will give it a try
