### ISSUE TITLE
Remove React develop console logs

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#202]
![image](https://github.com/getsentry/spotlight/assets/363802/1a57ee82-ce50-4761-b197-acd834c36bd8)

**Comment by HazAT** [comment]
I couldn't repro this locally anymore, but let's check to make sure

**Comment by Shubhdeep12** [comment]
Hey @HazAT I think you are mentioning React devtools logs?
If yes, since these are added in React apps when the browser app doesn't detect the React Devtools extension.

I think you can reproduce it by disabling/removing the extension.

**Comment by Lms24** [comment]
Can repro when disabeling dev tools (which for some reason don't work for me at all but whatever...):
![image](https://github.com/getsentry/spotlight/assets/8420481/fc42f547-fc8f-4382-87df-0447336124e5)

will fix
