### ISSUE TITLE
Spotlight hijacking common hotkey

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#218]
I have not looked at the implementation, but windows+shift+s (which is how you screenshot in Wondinws) is opening/closing Spotlight.

**Comment by Shubhdeep12** [comment]
Hi @dcramer this is implemented to handle open/close
![image](https://github.com/getsentry/spotlight/assets/43654389/2c8b72ec-de11-469b-9289-b07033986635)

It seems like metaKey which was added here keeping mac users in mind is also working for windows key in Windows.

**Comment by Lms24** [comment]
So, it seems like this is more OS dependent than I thought and `e.metaKey` is only emitted on `keydown` (at least on Mac OS). So for me right now on Mac Cmd+Shift+F12 doesn't work at all. 

On second thought, +S key combinations are probably quite prone to be assigned to save and screenshot commands so let's remove them for now and replace them with listening for `Ctrl`+`F12`. This is closer to dev tools which might work out better. Ideally we make this user-configurable at some point.

I'll quickly fix this.
