### ISSUE TITLE
Astro v4 integration giving "Cannot read properties of undefined" error

### ISSUE THREAD

**Issue by bustinbung** [getsentry/spotlight#232]
### Environment
Bun v1.0.15
Node v21.2.0

Astro v4.0.1
@sentry/astro v7.85.0
@spotlightjs/astro v0.0.25

### Steps to Reproduce
1. Run `bunx/npx astro add @spotlightjs/astro`
2. Install dependencies, modify `astro.config.ts`
3. Run `bun/npm run dev`
4. Astro fails with error.

### Expected Result
Expected Spotlight integration.

### Actual Result
Error message:
```
13:48:30 [ERROR] Cannot read properties of undefined (reading 'setupIntegrations')
  Stack trace:
    at /Users/justin/Developer/bustinbung.com/node_modules/vite/dist/node/chunks/dep-MF_y65BT.js:50117:9
    [...] See full stack trace in the browser, or rerun with --verbose.
```

Web console error:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

Output running with `--verbose`:
```
astro:vite Error when evaluating SSR module /Users/justin/Developer/bustinbung.com/src/pages/index.astro: failed to import "astro:scripts/page-ssr.js"
  astro:vite |- TypeError: Cannot read properties of undefined (reading 'setupIntegrations')
  astro:vite     at eval (astro:scripts/page-ssr.js:7:34)
  astro:vite     at async instantiateModule (file:///Users/justin/Developer/bustinbung.com/node_modules/vite/dist/node/chunks/dep-MF_y65BT.js:50117:9)
```

**Comment by dcramer** [comment]
Guessing failure is here:

```ts
import * as _SentrySDKForSpotlight from '@sentry/astro';

_SentrySDKForSpotlight.getClient().setupIntegrations(true);
```

We dont protect getClient() here, but I also dont know off hand when/why client would not be available. Can you confirm if @sentry/astro is installed?

**Comment by HazAT** [comment]
And also if `sentry` is setup before Spotlight
https://spotlightjs.com/setup/astro/
```
export default defineConfig({
  // Order matters here!  `sentry()` should come before `spotlightjs()`
  integrations: [sentry(), spotlightjs()]
});
```

**Comment by dcramer** [comment]
Updated the Astro package README in getsentry/spotlight@17c5bb1 to make sure we have no bad code samples:

**Comment by HazAT** [comment]
Added a fix and publish a new release now containing it: https://github.com/getsentry/spotlight/commit/7ba38099c347619ad36dc46ce2c24f77112303be

Sorry about that :)

<img width="844" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/a4918af8-c4e9-4d15-99fe-6a5edb3df01d">

**Comment by HazAT** [comment]
Fwiw @spotlightjs/astro@0.0.26 is released with a fix

**Comment by bustinbung** [comment]
Can confirm v0.0.26 fixed the issue for me. Thanks for the quick fix and resolution!
