### ISSUE TITLE
Span Tree for large traces should be collapsible 

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#236]
The tree is pretty much unusable for large Span Trees, we need to fix this with potentially collapsing the tree after a certain depth
![image](https://github.com/getsentry/spotlight/assets/363802/28002b62-52bd-44a3-9ea3-d02c92b901ef)

**Comment by Shubhdeep12** [comment]
Hi @HazAT 
- added a button to expand/collapse the tree
- Also, auto collapsed the tree after a depth of 5 ( we can increase it)


https://vimeo.com/892532538/1448e14bc0?share=copy
