### ISSUE TITLE
Clarify Sentry on homepage

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#243]
![image](https://github.com/getsentry/spotlight/assets/23610/75449697-51ad-4936-92c3-c89b834c9009)

Might just be worth it to say "brought to you by Sentry" on this page so its obvious

https://news.ycombinator.com/item?id=38548057

**Comment by Shubhdeep12** [comment]
Is this fine?
 ![Image](https://github.com/user-attachments/assets/e46e7c4e-4af4-4b55-9371-0858ecac6b58)
cc @BYK
