### ISSUE TITLE
Span waterfall displayed incorrectly on Firefox

### ISSUE THREAD

**Issue by cleptric** [getsentry/spotlight#262]
<img width="1706" alt="Screenshot 2023-12-11 at 11 29 31" src="https://github.com/getsentry/spotlight/assets/6617432/fa1cf698-0e3b-4691-a419-7759960e23dc">

_left is Firefox, right is Safari_

There might be an issue in Firefox, displaying the span waterfall wrong.

<img width="1135" alt="Screenshot 2023-12-11 at 11 28 03" src="https://github.com/getsentry/spotlight/assets/6617432/e1751a7a-96aa-4103-a2bd-e501e4d24284">

Sentry UI for reference.

**Comment by dcramer** [comment]
Interesting - I didnt think we resorted any of the spans (or at least not intentionally)

**Comment by Shubhdeep12** [comment]
just checked the span listing in overlay and found this line of code where we are sorting spans-

`  const sortedSpans = [...spans] 
    .sort(a => (a.parent_span_id ? 1 : 0));`

Although the original compare function is acceptable, it could lead to varied results in different browsers. According to conventions, the sort compare function should compare two values, yielding a positive, negative, or zero result.

After making this adjustment to the code, it appears that the results are now consistent across different browsers.
