### ISSUE TITLE
PHP Stack trace upside down

### ISSUE THREAD

**Issue by adnweedon** [getsentry/spotlight#294]
### Environment

I'm using the electron app v0.0.12, connected to PHP SDK 4.2.0.

### Steps to Reproduce

If I throw an exception in a controller in my code, and then view it in Spotlight, the stack trace preview at the top is the first file it hits in the system, and the code preview of the line where I throw the exception is at the very bottom of the stack if I scroll down.

### Expected Result

The sentry.io UI shows the line where an exception is triggered at the top, and then works its way out as the you go down the stack.

### Actual Result

I don't really want to put a screenshot as it reveals a load of our code structure, but the expanded code snippet with the highlighted line is the public/index.php, and if I scroll to the bottom and expand the last item in the trace, it is the line where I throw the Exception - the stack just needs reversing!

**Comment by Lms24** [comment]
Hmm we have some logic in spotlight's sentry data cache to reverse the stack frames list because SDKs seem to send it in different order. Maybe we're either not including the php SDK when reversing or we wrongfully include it when it's events don't need reversing 😓

**Comment by Shubhdeep12** [comment]
Hi @adnweedon 
if this is similar to this issue - https://github.com/getsentry/spotlight/issues/262
Please update the app and check again.
Thanks

**Comment by adnweedon** [comment]
I'ev just updated to 0.0.13 and it's still an issue!

**Comment by adnweedon** [comment]
It looks like https://github.com/getsentry/spotlight/commit/00c86f1b574450ab1a0f62861a688965325699e7 stopped reversing it, but I'm not sure what has changed between then and now that means it's upside down again, so I don't want to just undo the PHP bit?

**Comment by Shubhdeep12** [comment]
Hi @adnweedon
This is fixed in the recent version of Spotlight.
Please verify.
Thanks.

**Comment by adnweedon** [comment]
Yep, all sorted - thanks for that!
