### ISSUE TITLE
Electron Improvements

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#298]
- [x] Show error page with hint CMD+R if an error happens
- [x] #299
- [x] In case of an error, prompt user if it's ok to send an attachment with the payload so we can debug

**Comment by Shubhdeep12** [comment]
For Point 3 - https://github.com/getsentry/spotlight/issues/302

**Comment by Shubhdeep12** [comment]
For Point 1 - https://github.com/getsentry/spotlight/issues/304
