### ISSUE TITLE
Performance Tab Improvments

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#317]
Remove padding and have same styling as tabs (no background)
<img width="916" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/dd3c0794-d15e-425f-b7a8-2765fe44558f">

Let's remove the tabs while they are not working:
<img width="348" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/d9e40ec6-45d3-4572-8246-f721fb129b9c">

**Comment by Shubhdeep12** [comment]
Hi @HazAT this would be the final ui based on the inputs above. 
are we good with this?

![image](https://github.com/getsentry/spotlight/assets/43654389/c711fbd9-e465-40f2-b1e0-151b3cfd3259)
![image](https://github.com/getsentry/spotlight/assets/43654389/ba80530b-3b87-449f-bae1-11809465abb8)

**Comment by Shubhdeep12** [comment]
Hi @HazAT are we good with the changes?
Lets resolve this too, if we are good.

Thanks
