### ISSUE TITLE
Generic Breadcrumbs component

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#318]
When navigating into details it's sometimes hard to get back:
<img width="900" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/ebadebf9-a137-4def-9025-f5f7c0cf18b0">

Let's add a generic Breadcrumb component into Spotlight so navigating back is a breeze:

So in this case we can render it after the tabs and before the content:
And Show

`Queries > "GET 'ds::o:1:sliding_window_org_sample_rate'`
![image](https://github.com/getsentry/spotlight/assets/363802/0a947c4d-5467-4699-bb9c-6fad8f1c98a6)

Just simple text based breadcrumbs

**Comment by Shubhdeep12** [comment]
how about this @HazAT 
breadcrumbs which can be just plain text or can be link based on input. 
![image](https://github.com/getsentry/spotlight/assets/43654389/fef027c7-25bf-49d3-8182-f93d95d6d094)
