### ISSUE TITLE
Opening an Error crashes Spotlight

### ISSUE THREAD

**Issue by markushi** [getsentry/spotlight#331]
### Environment

Spotlight 0.0.14

### Steps to Reproduce

1. Install Spotlight
2. Use [`feat/spotlight`](https://github.com/getsentry/sentry-java/compare/main...feat/spotlight) branch for `sentry-java` on an Android project
3. Start sending an error
4. Open the error

### Expected Result

No crash.

### Actual Result

App crashes. 

Sentry issue: [link](https://sentry.sentry.io/issues/4915391450/events/1d6518ae409b40c6abc9b21aed63eaa8/)

This is due to the stack trace frames, as the `filename` attribute is not always present:
```json
{
    "filename": "View.java",
    "function": "run",
    "module": "android.view.View$PerformClick",
    "lineno": 29334,
    "native": false
},
{
    "function": "-$$Nest$mperformClickInternal",
    "module": "android.view.View",
    "lineno": 0,
    "native": false
}
```

**Comment by Shubhdeep12** [comment]
Hi @markushi  it would be great if you could follow this steps for sampling data https://spotlightjs.com/contribute/development/

And share the txt file created here. It will help us to debug the issue.
Actually, i cannot access the sentry internal link shared above. 

Thanks

**Comment by Lms24** [comment]
I think we should ensure that the `filename` type is optional when we process the event's stack trace. TS should then flag all the places where we currently don't check for definedness of it, just like in this case. 

@Shubhdeep12 this is the relevant part in Sentry:
![image](https://github.com/getsentry/spotlight/assets/8420481/23e265f6-11ef-4df0-aec9-0a58b15ec409)

**Comment by Shubhdeep12** [comment]
Thanks @Lms24 

Let's do it this way - https://github.com/getsentry/sentry/blob/c42c39f15becfbd4113f34942e27f2099a4b0cb8/static/app/components/events/interfaces/frame/defaultTitle/index.tsx#L95

as done in the Sentry app.
In the case of Java, we will prefer the Module name and for others, we'll check for the filename first and then fallback as the module name if the filename is not present.

**Comment by Lms24** [comment]
I'll leave the implementation details up to you but I'd like us to reflect in the `Event` type definitions (not sure where this is exactly but IIRC we have types within spotlight) that the filename could be missing. We should expect that this property is not always available.

**Comment by Shubhdeep12** [comment]
Yes EventFrame was having filename as the required type. made that optional too.

**Comment by markushi** [comment]
Here's an example Java crash:

[application_x_sentry_envelope-1706290053204.txt](https://github.com/getsentry/spotlight/files/14067733/application_x_sentry_envelope-1706290053204.txt)

**Comment by Shubhdeep12** [comment]
Thanks @markushi

**Comment by Shubhdeep12** [comment]
Hi @markushi 
This is fixed in latest version of Spotlight.
Please verify.
Thanks

**Comment by markushi** [comment]
Looking good now! Thanks!
<img width="1295" alt="image" src="https://github.com/getsentry/spotlight/assets/1411808/8d464f8f-78c5-4b67-84f0-f530300f4c75">
