### ISSUE TITLE
Clear Event button not clickable in Electron App

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#350]
Because the Drag header overlays it

The fix for this is, make the button hideable as an option, and don't show it in electron.

**Comment by Shubhdeep12** [comment]
Hi @HazAT can you please share a screenshot for this? 
it works fine when I run it locally, the button is clickable and visible.

![image](https://github.com/getsentry/spotlight/assets/43654389/91603293-a89c-46ff-9fec-ad8a76027945)

**Comment by HazAT** [comment]
This is how it looks for me
<img width="1012" alt="image" src="https://github.com/getsentry/spotlight/assets/363802/f1b3e6be-44b6-4428-9598-7f70e83cfdab">

I would still and an option and hide it in the electron app
there someone can just do CMD+R to achieve the same thing

**Comment by Shubhdeep12** [comment]
ok @HazAT let's remove this button for Electron App.
And we'll make reload and force-reload to clear events with their default functionality.
