### ISSUE TITLE
Query performance analysis with Django?

### ISSUE THREAD

**Issue by Mapiarz** [getsentry/spotlight#351]
Hi.

Is query performance analysis available with the Django integration? DB calls already seem to be captured in the trace details. 

Thanks for this neat piece of software.

**Comment by Shubhdeep12** [comment]
Hi @Mapiarz 
Currently, the Spotlight lists the queries found in traces under the Performance tab. However, no performance analysis has been captured for queries thus far.
Additionally, Spotlight should work with Django. You can refer to the installation guide here: https://spotlightjs.com/setup/other/
Please let us know if you encounter any issues.
Thanks

**Comment by BYK** [comment]
@Mapiarz can you provide more details about what you expect to see regarding query performance? I created #543 and we can add this task there if I can have some more clarity around it.

**Comment by BYK** [comment]
Closing due to lack of response, happy to re-open if/when we get one.
