### ISSUE TITLE
Platform icon shows on Errors but not Trace

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/spotlight#356]
<img width="518" alt="image" src="https://github.com/getsentry/spotlight/assets/1633368/3e4bae05-d921-49ee-b050-30d2def68f20">

<img width="580" alt="image" src="https://github.com/getsentry/spotlight/assets/1633368/32612485-9157-4bd2-957e-e2e4b846c44e">

SDKs it shows only:
<img width="476" alt="image" src="https://github.com/getsentry/spotlight/assets/1633368/b02e3675-8536-4461-a381-c1eba0567f17">

Spotlight version (is there a way to see it in the app?): I downloaded a minute ago from spotlightjs.com

**Comment by Shubhdeep12** [comment]
hi @bruno-garcia 

1. I think, there will be missing root transactions when no parents are present for events data coming from sentry sdk. ref: https://github.com/getsentry/spotlight/issues/140
2. Yes, it makes sense to include the spotlight version used by the electron app in the tab along with these points mentioned here - https://github.com/getsentry/spotlight/issues/82

**Comment by bruno-garcia** [comment]
got it, thanks for clarifying. if this ticket isn't helpful feel free to clsoe it then

**Comment by BYK** [comment]
I think the two separate tickets mentioned here cover the issue quite well so closing this one out.
