### ISSUE TITLE
Publish Spotlight standalone application for Linux

### ISSUE THREAD

**Issue by audkar** [getsentry/spotlight#367]
The standalone Spotlight Electron app is currently only available for MacOS. I would like to use it on Linux to work with the Sentry Android SDK.

**Comment by Shubhdeep12** [comment]
Hi @HazAT any thoughts here? should we create an electron app for Linux as well?

**Comment by BYK** [comment]
@audkar Sorry for the late response. Would the `npx @spotlightjs/spotlight` path or the `docker run` method work for you?

**Comment by audkar** [comment]
> the docker run method work for you?

I'd prefer to go with Docker myself.

**Comment by BYK** [comment]
Here you go then: https://spotlightjs.com/sidecar/docker

**Comment by BYK** [comment]
@audkar we also now have self-contained binaries equivalent to using `npx @spotlightjs/spotlight` without the need for `npx` or `node` on your system: https://github.com/getsentry/spotlight/releases/tag/%40spotlightjs%2Fspotlight%402.6.3
