### ISSUE TITLE
Not connected to Sidecar on Firefox

### ISSUE THREAD

**Issue by c-w** [getsentry/spotlight#376]
### Environment

* `yarn list | grep @spotlightjs/spotlight`: @spotlightjs/spotlight@1.2.13
* `firefox --version`: Mozilla Firefox 123.0
* `uname -a`: Linux pop-os 6.0.12-76060012-generic

### Steps to Reproduce

1. Run sidecar via `spotlight-sidecar 8969`
2. Open http://localhost:8969/ in Firefox

### Expected Result

Spotlight connects to sidecar.

### Actual Result

Spotlight displays "Not connected to Sidecar" and we see an error in the Javascript console:

```
Firefox can’t establish a connection to the server at http://localhost:8969/stream. [main-2f8fa137.js:79:22169](http://localhost:8969/assets/main-2f8fa137.js)

EventSource failed: error { target: EventSource, isTrusted: true, srcElement: EventSource, currentTarget: EventSource, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
[main-2f8fa137.js:79:22596](http://localhost:8969/assets/main-2f8fa137.js)
```

![](https://github.com/getsentry/spotlight/assets/1086421/57591de0-b054-400e-a084-21f281ac9270)

Note that the same steps work fine on Chrome (Version 122.0.6261.69).

**Comment by Shubhdeep12** [comment]
Hi @c-w thanks for writing in.

Looks like there is an error with firefox while connecting eventsource.

But I guess the moment some event is received it works fine, right?

**Comment by c-w** [comment]
@Shubhdeep12 I can’t answer that question as unfortunately I never got to that spot; it never connected across multiple client and server restarts. As an added observation: I doubt it’s a networking issue between the client and server as the “clear events” button issues the DELETE request successfully.
