### ISSUE TITLE
Sentry Plugin - Render received Envelope in Spotlight

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#377]
Add a new tab called: "Developer Info" in the Sentry Plugin, that renders every received envelope in a list.
And drill into the payload of every envelope item.
Visualize the Envelopes in a nice way - Headers/Items - and if the item is an event, consider using something like https://github.com/mac-s-g/react-json-view to print a nice JSON pretty.

We often use Spotlight for SDK development, and having a debug view of the payload can be immensely helpful.

**Comment by bruno-garcia** [comment]
Can we inspect all envelope payloads, like attachments, replays, etc?

**Comment by HazAT** [comment]
@bruno-garcia yes, great idea - every possible Envelope Item should be rendered

**Comment by bruno-garcia** [comment]
if attachment mime-type is known maybe we can render something. Like if `png` then just show it. Mp4 then `<video`?

@romtsn @brustolin imagine this while doing mobile replay? jeez

**Comment by markushi** [comment]
And if spotlight is enabled inside an app, we could send all (internal sentry) logs as breadcrumbs as well. Would be so much nicer compared to some console log output 🚀

**Comment by Shubhdeep12** [comment]
Great ideas, let me try it. 🚀

**Comment by Shubhdeep12** [comment]
Hey @bruno-garcia @markushi checkout new version of the spotlight.
We shipped this new tab.
Love to get your feedback and suggestions.

Also, how about if we add an option to edit the envelope data to see the impact of it?

**Comment by bruno-garcia** [comment]
Pinged SDK engineers I'm working with about it, I'll keep in mind next time I fire up an IDE :)
