### ISSUE TITLE
Overlay: DeveloperInfo tab feedback

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/spotlight#382]
- [x] Can we show event type in the Developer Info tab?
- [x] Can we have a button to clear all of the events in spotlight?
- [ ] Showing the types of values in the envelope details is a lot of visual noise. I would remove them.
- [x] The 'X' button in span details doesn't work.
 
originally posted by @lforst here - https://discord.com/channels/621778831602221064/1176977569678114847/1219954609473454120

**Comment by BYK** [comment]
Looks like we addressed all the issues mentioned here so closing out.
