### ISSUE TITLE
Spotlight sends extreme amount of data via SSE

### ISSUE THREAD

**Issue by jansedlon** [getsentry/spotlight#399]
### Environment

Tried v2 alpha and v1. Using sentry v8 and Remix integration.

### Steps to Reproduce

1. Followed the official instructions

### Expected Result

Well.. To work correctly and not sending 70MB of data in 1.5 minutes 😅

### Actual Result

It's all sluggish. The widget in my app and the spotlight app as well. Probably because of sending thousands of events.

Network tab in devtools

<img width="2554" alt="image" src="https://github.com/getsentry/spotlight/assets/13948180/6b2a0b3d-2e44-4761-9d60-9de7735e78db">
<img width="2211" alt="image" src="https://github.com/getsentry/spotlight/assets/13948180/044fe7b3-61a8-4f76-866d-47ce9b922ec5">
<img width="679" alt="image" src="https://github.com/getsentry/spotlight/assets/13948180/8021cfbd-edd2-4c7a-83d6-0ffde1450648">
<img width="827" alt="image" src="https://github.com/getsentry/spotlight/assets/13948180/07a4dd49-0e70-49a4-8754-b6037a802b71">
<img width="1435" alt="image" src="https://github.com/getsentry/spotlight/assets/13948180/ad011303-acd1-483c-baa5-81e8591311a3">

**Comment by Shubhdeep12** [comment]
Hi @jansedlon definitely something is wrong. 
First thing is spotlight v.2.0.0-alpha.1 supports sentry v8.


And is it possible for you to share a minimal reproduction example? because for the normal scenario, it is working fine for me.

**Comment by jansedlon** [comment]
Hey, i will try

**Comment by BYK** [comment]
Hi @jansedlon, are you still experiencing an issue?

**Comment by BYK** [comment]
We've made a bunch of improvements around this including a local cache with 1k item limit, local transport bypassing the sidecar for front-end etc.

Closing for now as we haven't heard back from the OP or anyone else having this issue. Happy to revisit if it is happening to other people.
