### ISSUE TITLE
To add custom sidecarUrl support in all integrations.


### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/spotlight#427]
- [ ] updating docs for custom intrgrations.
- [ ] to make sidecarURL (optional) in other intrgrations provided by Spotlight.
- [x] to pass the sidecarURL from Spotlight.init to the integration's options if the integrations array is paased by props while initiating Spotlight.

Originally posted here - #426

**Comment by BYK** [comment]
Closing this out as mostly wontfix as with the latest changes, even Sentry integration does not need/use the sidecar URL. From an architecture POV, the integrations should not directly interact with she sidecar anyway.

Finally, we do pass the `sidecarURL` to all integrations defined by `integrationNames` option which only applies to Vite plugin.
