### ISSUE TITLE
[macOS 15 Developer Beta or later] Spotlight Desktop App Crashes on launch

### ISSUE THREAD

**Issue by aguilaair** [getsentry/spotlight#484]
### Environment

Spotlight app for Apple Silicon version 1.0.0

Device is a MacBook Pro 16" 2021 with the M1 Pro

Fails to open on both MacOS 15 Developer Beta and 15.1 Developer Beta

### Steps to Reproduce

1. Download app from https://github.com/getsentry/spotlight/releases/download/%40spotlightjs/spotlight%402.0.0/Spotlight-1.0.0-arm64-mac.zip
2. Unzip, move to Applications folder
3. Attempt to open the app

### Expected Result

The app opens successfully.

### Actual Result

App attempted to launch but closed immediately. 

```
open -a Spotlight.app; log show --predicate 'subsystem == "io.sentry.spotlight"' --info --debug --last 10m
```
Yielded no logs:
```
Filtering the log data using "subsystem == "io.sentry.spotlight""
Timestamp                       Thread     Type        Activity             PID    TTL
--------------------------------------------------------------------------------------------------------------------
Log      - Default:          0, Info:                0, Debug:             0, Error:          0, Fault:          0
Activity - Create:           0, Transition:          0, Actions:           0
```

**Comment by BYK** [comment]
Hi, apologies! Looks like we never released a new version for Electron with the recent versions. I cut one now, can you try with this: https://github.com/getsentry/spotlight/releases/download/%40spotlightjs%2Fspotlight%402.3.1/Spotlight-1.1.4-arm64-mac.zip

I'll also update the link on the website. Thanks a lot for reporting :)

**Comment by BYK** [comment]
Well, turns out the links are (cleverly and as they should have been) automated so no action needed there. LMK if this latest build still has issues.

Until then, closing the ticket.

**Comment by aguilaair** [comment]
Unfortunately the app still fails to launch

**Comment by BYK** [comment]
Okay, I noticed I missed an important detail: this is on MacOS 15. Do you have another device to see if this actually runs? I've asked a friend with a Mac and they were able to run so I'm trying to isolate this to MacOS 15 and do the research that way.

**Comment by aguilaair** [comment]
Yep, it runs on other devices/OS Versions. It may have something to do with the Developer Beta, but I do not have any other devices running the Developer Beta, so we cannot rule out my device being the culprit.

**Comment by BYK** [comment]
@aguilaair thanks for confirming!

**Comment by BYK** [comment]
Okay found two other reports of an Electron app crashing on startup for macOS 15:

 - https://github.com/heyman/heynote/issues/232
 - https://www.reddit.com/r/MacOSBeta/comments/1eg7zaq/comment/lga1ol5/

The solution seems to be simple enough to use the latest version of Electron, which I'll try.

**Comment by BYK** [comment]
Here's a new release: https://github.com/getsentry/spotlight/releases/tag/%40spotlightjs%2Felectron%401.1.5

Can you give this a try?

**Comment by aguilaair** [comment]
It opened! Unfortunately, it is not quite loading the app yet:


![Image](https://github.com/user-attachments/assets/7319b547-66be-4a6b-aea1-44b0c96df015)

**Comment by BYK** [comment]
Yay! Quite sure I messed something up with the updates. Will try to resolve them tomorrow.

Thanks a lot again for all the help!

**Comment by BYK** [comment]
@aguilaair here's a new build which hopefully should fix the remaining issues: https://github.com/getsentry/spotlight/releases/tag/%40spotlightjs%2Felectron%401.1.6

**Comment by aguilaair** [comment]
Yep! I cannot see my device's logs, though (I'm using react native), but I suspect that's a separate issue.

**Comment by BYK** [comment]
Yay! Happy to help with the React Native issue too! Also, quick reminder that you can use `http://spotlight@localhost:8969/0` as your `DSN` for SDKs that doesn't support Spotlight natively yet.
