### ISSUE TITLE
[Featrue Request] Add captureconsole to Astro

### ISSUE THREAD

**Issue by erikdemarco** [getsentry/spotlight#507]
Please add captureconsole to astro.
I tried to add it but failed:

```
export default defineConfig({
  integrations: [sentry(), spotlightjs(), console()]
});
```

**Comment by BYK** [comment]
Hi @erikdemarco can you provide more details about what you are trying to achieve and what's the issue you are experiencing?

**Comment by erikdemarco** [comment]
Currently my working area is very cluttered with 4 column, i want to remove browser console, so sentry spotlight can show all the console message via this:

=> https://docs.sentry.io/platforms/javascript/configuration/integrations/captureconsole/

If spotlight can show all the browser's console message, i dont need console screen anymore, everything is shown in spotlight.

![Image](https://github.com/user-attachments/assets/abb6b3ea-c9fd-4f96-a023-4f526f22422b)


Also I have another question unrelated to this. When i installed spotlight via this command:

npx astro add @sentry/astro @spotlightjs/astro

Why that packages added to depedencies instead of devdepedencies in package.json? will it gets included during build time? How to make spotlight to be in dev only during installation?

**Comment by erikdemarco** [comment]
Currently my working area is very cluttered with 4 column, i want to remove browser console, so sentry spotlight can show all the console message via this:

=> https://docs.sentry.io/platforms/javascript/configuration/integrations/captureconsole/

If spotlight can show all the browser's console message, i dont need console screen anymore, everything is shown in spotlight.

![Image](https://github.com/user-attachments/assets/abb6b3ea-c9fd-4f96-a023-4f526f22422b)


Also I have another question unrelated to this. When i installed spotlight via this command:

npx astro add @sentry/astro @spotlightjs/astro

Why that packages added to depedencies instead of devdepedencies in package.json? will it gets included during build time? How to make spotlight to be in dev only during installation?

**Comment by BYK** [comment]
>If spotlight can show all the browser's console message, i dont need console screen anymore, everything is shown in spotlight.

I think what you are looking for is the `console` integration for Spotlight as the one for Sentry is used to collect breadcrumbs, not what you are asking. To enable this (along with the default `sentry` integration) you can modify your `astro.config.mjs` file as follows:

```js
export default defineConfig({
  integrations: [sentry(), spotlightjs({integrationNames: ['console', 'sentry']})],
});
```

If you have anything that logs a lot of stuff to the console (such as enabling `debug: true` in either Sentry SDK or Spotlight itself), this will cause it to hang though, so consider yourself warned.

>Why that packages added to depedencies instead of devdepedencies in package.json? will it gets included during build time? How to make spotlight to be in dev only during installation?

So for `@sentry/astro`, you need it on production too as I'm assuming you want to send events to your Sentry account. For `@spotlightjs/astro`, it should definitely be in `devDependencies`. I'll dig into `astro` CLI and integrations API to see if we can determine where the package ends up in. You would not ship Spotlight itself to production as it is a plugin that is only enabled for `astro dev` command.
