### ISSUE TITLE
Figure out good back navigation UX

### ISSUE THREAD

**Issue by Lms24** [getsentry/spotlight#51]
Currently, going back (e.g. from an error detail to the errors list) is broken. It used to be possible by pressing [ESC], however it had weird interchanges with pressing ESC on top level pages (e.g. errors/traces list). I think we should re-think how navigating back is done and most obvious for users. 

Ideas:
* Add a back button
* Intercept browser back button presses/history changes to navigate back. This might be tricky though with the React Router `MemoryRouter` 
* Bring back the [ESC] back functionality (is this obvious for users though?)
* Avoid explicit back logic but reset tabs when clicking onto the tabs?

**Comment by mydea** [comment]
I think it would be better UX to store the state _somehow_ in the URL. maybe as an opt in/out, via a fragment:

```
localhost:8000/users
// Open spotlight
localhost:8000/users#spotlight
// Go to some page
localhost:8000#spotlight-errors
```

or something like this. Then URL state can work properly. There is a small possibility of interplay if users use fragments for something important, but we could allow opting out of this...?
