### ISSUE TITLE
Same error is shown twice

### ISSUE THREAD

**Issue by rjzheng** [getsentry/spotlight#526]
### Environment

Version 1.1.9

### Steps to Reproduce

1. Integrate Spotlight with Expo/React Native app
2. Trigger an error
3. Sees the same error twice

### Expected Result

Only see the same error once.

### Actual Result

The same identical error with the id is shown twice
![Image](https://github.com/user-attachments/assets/841ed391-0c2b-4e87-8e3b-8c65f05a4093)

**Comment by BYK** [comment]
Hi @rjzheng thanks for the report and apologies for the late response, I was on a short break. Just released a new version that should have a fix to prevent this. Would be lovely if you can confirm that this works.

**Comment by rjzheng** [comment]
@BYK I tested it but now I don't see any Sentry errors logged in Spotlight in both v2.4.1 and v2.4.2. Here's the code I used to test
![Image](https://github.com/user-attachments/assets/80159936-12e6-4883-a791-fe4eb8e4e206)

You can see that the error is thrown but Spotlight doesn't log it
![Image](https://github.com/user-attachments/assets/eecb77f6-2fb4-46d4-ae26-1499a64960a5)

Though I do get the error in Sentry
![Image](https://github.com/user-attachments/assets/b905513c-8ddb-4587-8f3f-3a5dc0215cad)

**Comment by BYK** [comment]
@rjzheng - Ah, you are right. So when Spotlight UI is not inside your application, you need to enable the `SpotlightBrowser` integration from https://github.com/getsentry/sentry-javascript/blob/master/packages/browser/src/integrations/spotlight.ts

This will send the events to sidecar which are then relayed to the Electron app. [Our docs](https://docs.sentry.io/platforms/javascript/configuration/integrations/#adding-an-integration) show how to add this. You'd be adding `Sentry.spotlightBrowserIntegration()` to your integrations list.

**Comment by rjzheng** [comment]
We have `spotlight: true` in the init function, do we need that on top of that config? It was working before though.

![Image](https://github.com/user-attachments/assets/0e26b78f-f82d-4fca-a22c-c5e20aaa0fdb)

**Comment by BYK** [comment]
Due to the bundling requirements (to keep the main bundle light) on the browser side SDK, we cannot use `spotlight: true` without the extra integration code I shared above. I'll talk to JS SDK maintainers about this again to see if we can fall back to async includes to allow `spotlight: true` mechanism.

If it used to work in the past, I think it was because you were adding Spotlight to your main app too (and not to Electron).
