### ISSUE TITLE
Download links appear to be missing on https://spotlightjs.com/

### ISSUE THREAD

**Issue by adnweedon** [getsentry/spotlight#593]
### Environment

Browsing the web!

### Steps to Reproduce

I visited https://spotlightjs.com/ to check whether I was on the latest version, and found the download links were missing:

![Image](https://github.com/user-attachments/assets/3d7ba9a3-0a84-4203-af20-69b49bef2b4a)

### Expected Result

There used to be download buttons for Intel/Apple silicon macs

### Actual Result

No buttons, no version number!

**Comment by BYK** [comment]
Heya, thanks for the report! Looking into it now. Works locally so hard to debug.

**Comment by BYK** [comment]
Okay did a redeploy through Vercel and it looks like this is fixed now. Thanks again!
