### ISSUE TITLE
More visibility of HTTP Method on traces

### ISSUE THREAD

**Issue by adnweedon** [getsentry/spotlight#594]
I mainly use the Traces tab in Spotlight, and find it really helpful to see what is going on in my application. One thing I find frustrating, though, is that it doesn't show the HTTP method anywhere; in my application, the same URL could be a GET or a POST, and it would be really nice to be able to see that at a glance.

I've hacked together a quick example of the sort of thing I'd find helpful!

For example:
Current:
![Current](https://github.com/user-attachments/assets/afc2d788-ee14-4165-a6da-cb717d51d6cf)
![Current](https://github.com/user-attachments/assets/c294fbf0-6c43-4dd0-89a8-6fb11f4e714e)

Proposed example
![Proposed Example](https://github.com/user-attachments/assets/a43d050e-ce6b-42ea-8a44-eb8114a209bc)
 ![Proposed Example](https://github.com/user-attachments/assets/f50d2964-9d3d-444b-92dd-263371fbc719)

**Comment by BYK** [comment]
Thanks for the feedback @adnweedon! I agree this is quite infuriating and I'm kind of shocked we did not notice this earlier. I added the `request` context to errors and then @Shubhdeep12 brought that to traces but we still have 2 issues:

1. The request context is not showing up in trace context tab. I'm investigating this right now.
2. We should surface the method more prominently in the UI as you suggested. Looks like we do have this for Astro so I'll see what's different there. In the meantime adding @Shubhdeep12 as I think he's in the best position to address this with his UI reorg (check it out and let us what you think btw: #592)

**Comment by Shubhdeep12** [comment]
> Looks like we do have this for Astro so I'll see what's different there

I guess in some SDKs, we get the request method added to `description` of span. Maybe that is the reason, we are not adding it on UI with title.

Reference:
See the difference in title of Laravel and astro![Image](https://github.com/user-attachments/assets/490f6185-01db-45d3-8ccb-0f473d9f5d4b)

**Comment by adnweedon** [comment]
Thanks so much for sorting this - sorry I didn't respond sooner, I've broken my GitHub notifications somehow 😅

**Comment by BYK** [comment]
@adnweedon no worries and thank _you_ for the report! @Shubhdeep12 has some more improvements planned but I think it is in a much better state now thanks to your feedback.
