### ISSUE TITLE
Breaking CSP with `new Function()`

### ISSUE THREAD

**Issue by sandstrom** [getsentry/spotlight#609]
There is a CSP violation in our tests due to an invocation of `new Function("return this")` (this is a legacy alternative to `globalThis`). We've traced this to `@spotlightjs/overlay` having a dependency on `react-json-view`, which in turn has a dependency `istanbul-lib-instrument` which contains the problematic code.

`react-json-view` was [updated](https://github.com/mac-s-g/react-json-view/issues/316) in version 1.20.3 to conditionally import istanbul when `NODE_ENV=test` only, which I assume is why this CSP violation does not happen in development and production. `istanbul-lib-instrument` itself was [updated](https://github.com/istanbuljs/istanbuljs/pull/734) in version 6.0.1 to mitigate the problem, but `react-json-view` still uses version 4.0.3.

Note also that your version of react-json-view is no longer maintained, but there are replacements such as https://github.com/microlinkhq/react-json-view.

We've worked around this in our code base, but would be nice if Spotlight would update its dependencies so that this would go away.

**Comment by BYK** [comment]
Hi @sandstrom, thanks a lot for bringing this up! I was very uncomfortable using that unmaintained package but didn't realize a fork existed. I updated our dependencies to use the fork instead which doesn't seem to have the `istanbul-lib-instrument` dependency. Can you confirm so I can merge?

**Comment by BYK** [comment]
Also, special thanks for the awesome bug report with all the context and everything!

**Comment by sandstrom** [comment]
Thanks @BYK! 🎉 

Since it's already merged, we'll try it out after the next release or from master if we can get that working. Will write back here if we run into any trouble, but this should have fixed it!

(I think it's slightly more complicated to install npm packages from Github when using mono-repos, but I'll try [this](https://gitpkg.vercel.app/about))

**Comment by william-stacken** [comment]
@BYK I have tested the update now in a fork where I generated the `dist` folder using `npm run build` and used the GitPkg suggestion by @sandstrom above, and it seems to work! But I had to update `package.json` to export the new `iife` file, or I ran into problems.
https://github.com/william-stacken/sentry-spotlight/commit/63217fc824d4c9757e7ddfcf60a1be7aa3ec456a

Did I generate the `dist` folder incorrectly, or is there a mistake in `package.json`?

**Comment by BYK** [comment]
@william-stacken Spotlight uses `pnpm` and we manage it using [Volta](https://docs.volta.sh/advanced/pnpm). You may wanna try that. Steps to get a build:

1. Run `pnpm install` in the root of project
2. Run `pnpm --filter @spotlightjs/overlay... build`
3. Profit

If all fails, we should be cutting a new release later today (still several hours ahead)

**Comment by william-stacken** [comment]
@BYK I noticed that a new release was made now. But I still have the same problem that `ember_auto_import` fails to import spotlight. It searches for `sentry-spotlight.umd.cjs` since it is specified in [`package.json`](https://github.com/getsentry/spotlight/blob/8dfb11aa977e6cba43ccf0455c67d8bb00503b77/packages/overlay/package.json#L26). But the file it should actually import is `sentry-spotlight.iife.js`, and from my testing it is enough to change the filename under the `exports` field in `package.json` to resolve the problem. If you think it is reasonable I can open a pull request for this?

**Comment by BYK** [comment]
@william-stacken this looks like a completely separate issue (and a valid one) so filed #625. Simply renaming that field to `IIFE` is not great as:

1. UMD is not equivalent to IIFE
2. We inject some code at the end of IIFE to auto-init Spotlight so this can be a drop-in script tag on pages. Mainly for https://spotlightjs.com/setup/html/

I'm curious if your build system would be able to consume the `es` module so we can drop the `require` export. Alternatively we can build a `umd` bundle or `cjs` bundle, whichever is better for people.
