### ISSUE TITLE
Missing types for @spotlightjs/sidecar/vite-plugin v1.9.2

### ISSUE THREAD

**Issue by MattyBalaam** [getsentry/spotlight#610]
### Environment

Node 20.x

There appear to be missing type declaration in spotlightjs/sidecar/vite-plugin v1.9.2.

### Steps to Reproduce

See the package.json file:

 ![Image](https://github.com/user-attachments/assets/47b3caae-34cb-4958-b1f6-1084cd9dedd8)

### Expected Result

Types should be included by default

### Actual Result

`Could not find a declaration file for module '@spotlightjs/sidecar/vite-plugin'. '/Users/XXXX/node_modules/@spotlightjs/sidecar/src/vite-plugin.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/spotlightjs__sidecar` if it exists or add a new declaration (.d.ts) file containing `declare module '@spotlightjs/sidecar/vite-plugin';`ts(7016)`

**Comment by BYK** [comment]
Yeah looks like since that file is not compiled at all, we don't generate anything. I'll fix this, thanks for bringing it up!

**Comment by BYK** [comment]
@MattyBalaam - btw can you share how you are using the Vite plugin for the sidecar? We actually have a "better" vite-plugin over at `@spotlightjs/spotlight` which automatically injects the overlay along with starting the sidecar.

**Comment by MattyBalaam** [comment]
I followed the guide here: https://spotlightjs.com/setup/remix/

**Comment by MattyBalaam** [comment]
Thanks, just updated to the other plugin and everything is working

**Comment by BYK** [comment]
@MattyBalaam nice! With that, you should not need the `@spotlightjs/overlay` package and any config/import related to that.
