### ISSUE TITLE
Remix/React hydration warning for style on body

### ISSUE THREAD

**Issue by MattyBalaam** [getsentry/spotlight#613]
Spotlight appears to be injecting styles onto the body client side. `style="overflow: auto;"`

### Environment

"@spotlightjs/spotlight": "2.7.0",
"@remix-run/node": "2.15.0"

### Steps to Reproduce

Follow instructions to initialise in development mode

### Expected Result

No warnings logged to console.

### Actual Result

"Warning: Extra attributes from the server: style"

**Comment by BYK** [comment]
Great find! Looks like this is the cause: https://github.com/getsentry/spotlight/blob/76bc48618812f260b8788b83926fa36fbd9ade35/packages/overlay/src/App.tsx#L217-L225

I'll see what we can do about this now.
