### ISSUE TITLE
Spotlight Sidecar Hangs Indefinitely on Startup When VSCode is Port Forwarding 8969 to Nothing

### ISSUE THREAD

**Issue by mattico** [getsentry/spotlight#627]
### Environment

Tested:
Spotlight 2.8.1 win-x64, also via `npx @spotlightjs/spotlight`

### Steps to Reproduce

1. Run spotlight's sidecar within a VSCode context which forwards ports to the host (WSL, DevContainer, etc.)
2. Stop the sidecar but leave VSCode open.
3. Outside of VSCode, start the sidecar.

### Expected Result

Upon starting the sidecar, it will either work normally or log `Sidecar is already running on port`.

### Actual Result

The Spotlight logo is printed but then nothing happens. Control-C prints `🔎 [Spotlight] Bye.`. Attaching a node debugger shows that `isSidecarRunning` never resolves. I'm not sure why the request timeout isn't working. Curl times out properly:

    curl.exe http://localhost:8969/health -m 2
    curl: (28) Operation timed out after 2002 milliseconds with 0 bytes received

Removing the forwarded port in VSCode fixes the issue.

**Comment by BYK** [comment]
Thanks a lot for the report @mattico! This sure is annoying and I fixed a tangential issue in #571. I'll see how we can handle this.
