### ISSUE TITLE
Breadcrumbs tab in error doesn't show available breadcrumbs

### ISSUE THREAD

**Issue by buenaflor** [getsentry/spotlight#630]
### Environment

Spotlight on mac silicon, version **1.2.2**

### Steps to Reproduce

1. Trigger error in Flutter SDK
2. Check breadcrumbs in the error
3. Spotlight says no breadcrumbs available

### Expected Result

Breadcrumbs are displayed

### Actual Result

No breadcrumbs in error view although breadcrumbs can be found in the envelope

![Image](https://github.com/user-attachments/assets/6058b79d-f289-4a02-ac61-d9af5011d117)

<img width="888" alt="Image" src="https://github.com/user-attachments/assets/23395e3e-f108-4530-b6de-df077b8a3586" />

**Comment by BYK** [comment]
@buenaflor can you share the envelope data so I can test and fix this locally?

**Comment by BYK** [comment]
Was able to reproduce with the new `envelope_with_screenshot.bin` envelope. Investigating...

**Comment by BYK** [comment]
Found it: we only were showing "simple" breadcrumbs with the `message` attribute while flutter is sending us "rich" breadcrumbs with `data` in it. Adding support with `JsonViewer`.
