### ISSUE TITLE
SDKs should become supplemental information

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#82]
This is a carry over from hackweek when it was fully Sentry-coupled. Its still valuable information, but maybe we can combine SDKs with some kind of Meta tab that also includes integration information and versions?

e.g.

```
[Integrations]

Sentry - 1.0
├── @sentry/node - 3s ago - blah blah
└── @sentry/browser - blah blah
Astro - 1.0
```

Current display:

![image](https://github.com/getsentry/spotlight/assets/23610/4c509062-0a79-40ad-b308-e53b2fb16639)

**Comment by HazAT** [comment]
We should just find a place where to embed the data somewhere on events/traces etc
maybe a small icon with a tooltip shows the info

**Comment by Shubhdeep12** [comment]
Hey @HazAT are you talking about adding something like this in trace and error detail pages - https://vimeo.com/921698224/ee9fcb4039
