### ISSUE TITLE
Scroll issues with Spotlight overlay

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#94]
There are two key issues present here:

1. Width/overflow is not correct at least on the trace view, as there should not be a horizontal scrollbar in this case.
2. The vertical scroll is actually masking another issue, where its not taking over page focus entirely. Meaning you can scroll the main page when you're trying to scroll this dialog.

![image](https://github.com/getsentry/spotlight/assets/23610/10612182-66d4-4d1c-9166-882bed5987c4)

**Comment by HazAT** [comment]
Should be fixed
