### ISSUE TITLE
Sidecar: OOM happens in undefined scenarios

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#95]
Not entirely sure what's going on - I noticed it with what appeared to be a recursive serialization error (when trying to serialize from `@sentry/remix` to connect()).

We may want to 1. reduce max items, 2. add a bytes-based eviction policy to the ring buffer.

**Comment by HazAT** [comment]
Fixed in https://github.com/getsentry/spotlight/commit/fedeb478ca15f439c73d5459e38a867279a05352
